[project]
name = "holisticon-recrutiment"
version = "0.1.0"
description = "Task for Holisticon Recrutiment"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-adk==1.23.0",
    "google-genai==1.61.0",
    "pydantic==2.12.5",
]

[project.urls]
repository = "https://github.com/k-sobczyk/holisticon-recrutiment"

[dependency-groups]
dev = [
]
test = [
   "pytest==8.4.1",
   "coverage[toml]==7.10.3",
]
lint = ["pre-commit==4.3.0", "pyright==v1.1.403", "ruff==0.12.8"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
filterwarnings = [
    "error",
    "ignore::pytest.PytestUnraisableExceptionWarning",
    "ignore::ResourceWarning",
]
xfail_strict = true
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"

[tool.ruff]
line-length = 120
target-version = "py313"
include = ["app/**/*.py", "tests/**/*.py"]
exclude = []

[tool.ruff.lint]
extend-select = ["Q", "RUF100", "C90", "UP", "I", "D"]
flake8-quotes = { inline-quotes = "single", multiline-quotes = "double" }
isort = { combine-as-imports = true, known-first-party = ["app"] }
mccabe = { max-complexity = 15 }
ignore = [
   "D100", # ignore missing docstring in module
   "D101", # ignore missing docstring in public class
   "D102", # ignore missing docstring in public method
   "D103", # ignore missing docstring in public function
   "D104", # ignore missing docstring in public package
   "D105", # ignore missing docstring in magic methods
   "D107", # ignore missing docstring in __init__ methods
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
docstring-code-format = true
quote-style = "single"

[tool.coverage.run]
source = ["app"]
branch = true

[tool.coverage.report]
precision = 2
exclude_lines = [
   "pragma: no cover",
   "raise NotImplementedError",
   "if TYPE_CHECKING:",
   "@overload",
]

[tool.pyright]
#typeCheckingMode = "strict"
reportUnnecessaryTypeIgnoreComment = false
reportMissingTypeStubs = false
include = ["app"]
venvPath = ".venv"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["app"]
